## chapter 4

#### example 1: initialize

- kaiming init(HE init)
    + kaiming_normal() and kaiming_uniform_()
    + fan_in: number of neurons in input layer
    + *applied with ReLU
- xavier init(Glorot init)
    + xavier_normal() and xavier_uniform_()
    + fan_in & fan_out

In [ ]:
import torch
from torch import nn

linear1 = nn.Linear(5, 3)
nn.init.constant_(linear1.weight, 3)
print(linear1.weight.data)

linear2 = nn.Linear(5, 3)
nn.init.kaiming_uniform_(linear2.weight, 3)
print(linear2.weight.data)

linear3 = nn.Linear(5, 3)
nn.init.xavier_uniform_(linear3.weight, 3)
print(linear3.weight.data)



tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([[-0.0220, -0.3344, -0.1449, -0.3027, -0.0117],
        [ 0.3353,  0.2272, -0.1427, -0.2562,  0.1757],
        [ 0.2539, -0.0502,  0.1393,  0.1944, -0.0460]])
tensor([[ 0.2000, -0.8540, -1.7212,  2.2354, -2.2150],
        [-0.1121,  1.9538, -0.2588,  0.0030,  1.5081],
        [ 0.7934, -2.0486,  0.6839, -0.1625,  0.3325]])


#### example 2: build neuron network

In [9]:
import torch
from torch import nn
from torchsummary import summary

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden1 = nn.Linear(3, 3)
        self.hidden2 = nn.Linear(3, 2)
        self.output = nn.Linear(2, 2)

        nn.init.xavier_normal_(self.hidden1.weight)
        nn.init.zeros_(self.hidden1.bias)
        nn.init.kaiming_normal_(self.hidden2.weight)
        nn.init.zeros_(self.hidden2.bias)

    def forward(self, x):
        x = torch.sigmoid(self.hidden1(x))
        x = torch.relu(self.hidden2(x))
        x = torch.softmax(self.output(x), dim=-1)
        return x
    

if __name__ == '__main__':
    model = MyModel()
    data = torch.randn(5, 3)
    print(f'data = {data}')
    output = model.forward(data)
    print(f'output = {output}')
    print('parameter:')
    summary(model, input_size=(5, 3))

data = tensor([[-0.0999,  0.5515,  1.1632],
        [-1.2901, -1.1608, -1.4728],
        [-0.1279,  0.5652,  0.4114],
        [ 0.6140,  1.7854, -0.2643],
        [ 0.0645,  0.3913, -1.6623]])
output = tensor([[0.5532, 0.4468],
        [0.5443, 0.4557],
        [0.5563, 0.4437],
        [0.5702, 0.4298],
        [0.5660, 0.4340]], grad_fn=<SoftmaxBackward0>)
parameter:
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 5, 3]              12
            Linear-2                 [-1, 5, 2]               8
            Linear-3                 [-1, 5, 2]               6
Total params: 26
Trainable params: 26
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


#### example 3: loss function

- loss function = cost func = objective func = error func
- designed for evaluating fitting condition
- classification problem:
    + CrossEntropyLoss
    + BCELoss (Binary Category Entropy)
- regression problem:
    + MAE: mean absolute error (not smooth)
    + MSE: mean squared error (gradient explosion might occur)
    + Smooth L1: combine MAE and MSE