## chapter2: tensor & numpy

#### example1

In [8]:
import torch
import numpy

t1 = torch.randint(1, 10, (2, 3))
n1 = t1.numpy()
print(f't1 = {t1}, n1 = {n1}\n')
print(f'type of n1 = {type(n1)}\n')

t2 = torch.randint(1, 10, (2, 3))
n2 = t2.numpy().copy()
t2[0] = 255
print(f't2 = {t1}, n2 = {n2}\n')
print(f'type of n2 = {type(n2)}\n')

n3 = numpy.array([[1,2,3], [4,5,6]])
t3 = torch.from_numpy(n3)
print(f't3 = {t3}, n3 = {n3}\n')

num1 = torch.tensor(1).item()
print(f'num1 = {num1}, type = {type(num1)}\n')

t1 = tensor([[3, 8, 6],
        [3, 1, 5]]), n1 = [[3 8 6]
 [3 1 5]]

type of n1 = <class 'numpy.ndarray'>

t2 = tensor([[3, 8, 6],
        [3, 1, 5]]), n2 = [[1 3 5]
 [7 6 9]]

type of n2 = <class 'numpy.ndarray'>

t3 = tensor([[1, 2, 3],
        [4, 5, 6]]), n3 = [[1 2 3]
 [4 5 6]]

num1 = 1, type = <class 'int'>



#### example2

In [22]:
import torch

t1 = torch.tensor([1, 2, 3, 4, 5])
tmp1 = torch.tensor([[1,2,3],
                     [4,5,6]])
tmp2 = torch.tensor([[1,2],
                     [3,4],
                     [5,6]])

t2 = torch.add(t1, t1)
print(t2)
t3 = t1 + 10
print(t3)
t4 = t1.neg()
print(t4)
t5 = torch.matmul(t1, t1)
print(t5)
t6 = tmp1 @ tmp2
print(t6)



tensor([ 2,  4,  6,  8, 10])
tensor([11, 12, 13, 14, 15])
tensor([-1, -2, -3, -4, -5])
tensor(55)
tensor([[22, 28],
        [49, 64]])


#### example3

In [32]:
import torch

tmp1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
    ])

print(tmp1.exp())
print(tmp1.log())
print(f'min = {tmp1.min()}, max = {tmp1.max()}')
print(f'sum0 = {tmp1.sum(0)}, sum1 = {tmp1.sum(1)}, sum = {tmp1.sum()},')
print(tmp1.float().mean())

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
min = 1, max = 6
sum0 = tensor([5, 7, 9]), sum1 = tensor([ 6, 15]), sum = 21,
tensor(3.5000)


#### example4

In [4]:
import torch

tmp1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
    ])

tmp2 = torch.randint(0, 10, (3, 3, 3))

print(tmp1[0, :])
print(tmp1[:, 1])
print(tmp1[[0,1],[1,2]])
print(tmp1[[[0],[1]],
           [[1,2]]])
print(tmp1[:2, :2])

print('-' * 30)
print(tmp2)
print(tmp2[1, :, :])
print(tmp2[1, 1, :])

tensor([1, 2, 3])
tensor([2, 5])
tensor([2, 6])
tensor([[2, 3],
        [5, 6]])
tensor([[1, 2],
        [4, 5]])
------------------------------
tensor([[[4, 6, 7],
         [0, 8, 7],
         [3, 8, 1]],

        [[3, 9, 1],
         [2, 9, 2],
         [1, 9, 3]],

        [[5, 8, 3],
         [4, 3, 8],
         [1, 7, 6]]])
tensor([[3, 9, 1],
        [2, 9, 2],
        [1, 9, 3]])
tensor([2, 9, 2])


#### example4

In [ ]:
import torch
tmp1 = torch.tensor([1, 2, 3, 4, 5])
print(f'tmp1 = {tmp1}')

tmp2 = torch.randint(0, 10, (2, 2, 3))
tmp3 = torch.randint(0, 10, (2, 2, 3))
#tmp3 = torch.randint(0, 10, (1, 2, 3, 1, 1))
print(tmp2)
print(tmp2.is_contiguous())
#print(tmp3)

print(tmp1.unsqueeze(0))
print(tmp1.unsqueeze(1))
print(tmp2.reshape((2, 6)))
print(tmp2.reshape((1, 12)))
print(tmp2.view(1, 12))
#print(tmp3.squeeze())
print(tmp2.transpose(1, 2))
t1 = tmp2.permute(2, 0, 1)
print(t1.contiguous().view(2, 6))

print('-' * 30)


tmp1 = tensor([1, 2, 3, 4, 5])
tensor([[[3, 0, 6],
         [2, 2, 0]],

        [[4, 1, 6],
         [5, 2, 6]]])
True
tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[3, 0, 6, 2, 2, 0],
        [4, 1, 6, 5, 2, 6]])
tensor([[3, 0, 6, 2, 2, 0, 4, 1, 6, 5, 2, 6]])
tensor([[3, 0, 6, 2, 2, 0, 4, 1, 6, 5, 2, 6]])
tensor([[[3, 2],
         [0, 2],
         [6, 0]],

        [[4, 5],
         [1, 2],
         [6, 6]]])
tensor([[3, 2, 4, 5, 0, 2],
        [1, 2, 6, 0, 6, 6]])
------------------------------
tensor([[[[3, 0, 6],
          [2, 2, 0]],

         [[1, 0, 0],
          [3, 3, 3]]],


        [[[4, 1, 6],
          [5, 2, 6]],

         [[2, 9, 5],
          [6, 8, 9]]]])
tensor([[[3, 0, 6],
         [2, 2, 0],
         [1, 0, 0],
         [3, 3, 3]],

        [[4, 1, 6],
         [5, 2, 6],
         [2, 9, 5],
         [6, 8, 9]]])


In [24]:
import torch
tmp1 = torch.randint(0, 10, (2, 2, 3))
tmp2 = torch.randint(0, 10, (2, 2, 3))

print(tmp1)
print(tmp2)

print(torch.stack([tmp2, tmp1], 2))
print(torch.cat([tmp2, tmp1], 0))

tensor([[[1, 1, 1],
         [9, 6, 9]],

        [[8, 0, 3],
         [3, 1, 9]]])
tensor([[[5, 5, 9],
         [6, 7, 7]],

        [[6, 8, 8],
         [7, 7, 4]]])
tensor([[[[5, 5, 9],
          [1, 1, 1]],

         [[6, 7, 7],
          [9, 6, 9]]],


        [[[6, 8, 8],
          [8, 0, 3]],

         [[7, 7, 4],
          [3, 1, 9]]]])
tensor([[[5, 5, 9],
         [6, 7, 7]],

        [[6, 8, 8],
         [7, 7, 4]],

        [[1, 1, 1],
         [9, 6, 9]],

        [[8, 0, 3],
         [3, 1, 9]]])


#### example5

In [10]:
import torch

w = torch.tensor(10, requires_grad=True, dtype=torch.float)
loss = 2 * w ** 2
loss.backward()
w.data = w.data - 0.01 * w.grad
print(f'w_new = {w}')

w_new = 9.600000381469727


In [16]:
import torch

x = torch.tensor(data=10, requires_grad=True, dtype=torch.float)
for i in range (1, 1000):
    loss = x ** 2 + 20
    loss.backward()
    x.data -= 0.01 * x.grad
    x.grad.zero_()
print(f'x = {x}, y = {loss}')

x = 1.7173128696867934e-08, y = 20.0
